### ISSUE TITLE
Precise and Cloud Archive Icehouse - Unable to boot an image

### ISSUE THREAD

**Issue by retr0h** [dguerri/vagrant-ansible-openstack#1]
Are you able to boot an instance?  I am simply running `scripts/4-create-first-istance.sh` and encounter the following error.  I am running the virtual box vagrant provider, which you may not be doing.  However, that error looks to be related to configuration of ml2 in most of the research I have done.

```
86ab1088d2d 511745f5c9b24a618e7e59345f00ddfc] Attempting to build 1 instance(s) uuids: [u'8f3cdb0f-df29-4704-b617-5d81943f0121']
2014-10-11 01:25:12.063 13948 ERROR nova.scheduler.filter_scheduler [req-46266cc2-ea33-418c-a00b-608e04f357c5 4d38f6ca5ce949e78110086ab1088d2d 511745f5c9b24a618e7e59345f00ddfc] [instance: 8f3cdb0f-df29-4704-b617-5d81943f0121] Error from last host: compute (node compute): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1329, in _build_instance\n    set_access_ip=set_access_ip)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 393, in decorated_function\n    return function(self, context, *args, **kwargs)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1741, in _spawn\n    LOG.exception(_(\'Instance failed to spawn\'), instance=instance)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/excutils.py", line 68, in __exit__\n    six.reraise(self.type_, self.value, self.tb)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1738, in _spawn\n    block_device_info)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2284, in spawn\n    write_to_disk=True)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 3478, in to_xml\n    disk_info, rescue, block_device_info)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 3292, in get_guest_config\n    flavor)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/vif.py", line 384, in get_config\n    _("Unexpected vif_type=%s") % vif_type)\n', u'NovaException: Unexpected vif_type=binding_failed\n']
```

**Comment by dguerri** [comment]
Closing the issue as works-for-me :)
